"""add status_change_count to support_tickets

Revision ID: 009
Revises: 008
Create Date: 2026-08-16 22:38:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '009'
down_revision = '008'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('status_change_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'status_change_count')
    # ### end Alembic commands ###
